{{- if .Values.enterprise.licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-license
  labels:
    app: swarmai
    release: {{ .Release.Name }}
type: Opaque
data:
  license-key: {{ .Values.enterprise.licenseKey | b64enc | quote }}
{{- end }}
