# SwarmAI Research Example - Simplified Local Configuration
# Direct Java execution without entrypoint script

services:
  research-app:
    image: swarmai-research:latest
    container_name: research-competitive-analysis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL=llama3.2:3b
      - SPRING_AI_OLLAMA_CHAT_OPTIONS_TEMPERATURE=0.7
      - SWARMAI_DEFAULT_MAX_RPM=15
      - SWARMAI_DEFAULT_MAX_EXECUTION_TIME=600000
      - SWARMAI_DEFAULT_VERBOSE=true
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC
      - LOGGING_LEVEL_AI_INTELLISWARM_SWARMAI=DEBUG
    ports:
      - "8080:8080"
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Override entrypoint to run Java directly
    entrypoint: ["java"]
    command: ["-jar", "app.jar", "competitive-analysis"]
    networks:
      - research-network

networks:
  research-network:
    driver: bridge