package ai.intelliswarm.swarmai.skill;

/**
 * Lifecycle status for generated skills.
 *
 * CANDIDATE → VALIDATED → ACTIVE → PROMOTED → PERMANENT
 */
public enum SkillStatus {
    CANDIDATE,   // Just generated by LLM, not yet tested
    VALIDATED,   // Passed sandbox tests and security scan
    ACTIVE,      // In use within current workflow execution
    PROMOTED,    // Met promotion threshold (5+ uses, 70%+ success)
    PERMANENT    // Persisted to disk, loaded on startup
}
